language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test

script:
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    recipients:
      - oahehc@gmail.com
    on_success: always
    on_failure: always